import type { Metadata } from "next";
import type { ReactNode } from "react";

import { siteConfig } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "Review the terms governing your use of Zaprill, including payments, AI outputs, and acceptable use.",
  alternates: {
    canonical: "/terms"
  },
  openGraph: {
    title: "Terms & Conditions — Zaprill",
    description: "Review the terms governing your use of Zaprill, including payments, AI outputs, and acceptable use.",
    type: "website",
    images: ["/og"]
  },
  twitter: {
    card: "summary",
    title: "Terms & Conditions — Zaprill",
    description: "Review the terms governing your use of Zaprill, including payments, AI outputs, and acceptable use."
  }
};

const lastUpdated = "April 12, 2026";

export default function TermsPage() {
  return (
    <section className="bg-background py-20 transition-colors duration-300">
      <div className="container max-w-[720px]">
        <h1 className="text-foreground">Terms &amp; Conditions</h1>
        <p className="mt-3 text-sm text-muted-foreground">Last updated: {lastUpdated}</p>
        <div className="mt-10 space-y-10">
          <TermsSection title="1. Acceptance of terms">
            By accessing or using Zaprill, you agree to these Terms &amp;
            Conditions. If you do not agree, please do not use the service.
          </TermsSection>
          <TermsSection title="2. Description of service">
            Zaprill provides AI-powered resume analysis, salary insights, job
            matching, resume improvement tools, and related career intelligence
            features through its website and application.
          </TermsSection>
          <TermsSection title="3. User accounts and eligibility">
            You must be at least 18 years old to use the service. Some features
            may require an account, and you are responsible for maintaining the
            confidentiality and accuracy of your account information.
          </TermsSection>
          <TermsSection title="4. Uploaded content">
            You retain ownership of the resume and other content you upload. By
            using the service, you grant Zaprill a limited licence to process,
            store, analyse, and display that content as required to operate and
            improve the service.
          </TermsSection>
          <TermsSection title="5. AI-generated outputs">
            Salary insights, job matches, resume suggestions, and other outputs
            are indicative only. They are not guaranteed, and they do not
            constitute financial, legal, or professional advice.
          </TermsSection>
          <TermsSection title="6. Credits and payments">
            Paid plans and credits, if offered, are billed according to the plan
            selected at purchase. Used credits are non-refundable. Subscription
            plans may be eligible for pro-rated refunds on unused subscription
            months where required by law or explicitly approved by Zaprill.
          </TermsSection>
          <TermsSection title="7. Prohibited use">
            You may not scrape the platform, submit false or misleading resumes,
            abuse the service, attempt to reverse engineer proprietary systems, or
            resell outputs generated by Zaprill without written permission.
          </TermsSection>
          <TermsSection title="8. Advertising">
            The marketing site at zaprill.com may display third-party advertising,
            including Google AdSense placements, to support free access to content
            and tools.
          </TermsSection>
          <TermsSection title="9. Intellectual property">
            Zaprill and its licensors own the platform, brand assets, model
            workflows, interface designs, and related intellectual property except
            for user-provided content.
          </TermsSection>
          <TermsSection title="10. Limitation of liability">
            To the maximum extent permitted by law, Zaprill is not liable for
            indirect, incidental, special, consequential, or punitive damages, or
            for business losses arising from use of the service.
          </TermsSection>
          <TermsSection title="11. Governing law">
            These Terms are governed by the laws of India. Courts in Mumbai,
            Maharashtra will have jurisdiction over disputes arising out of or in
            connection with the service.
          </TermsSection>
          <TermsSection title="12. Contact">
            Questions about these Terms can be sent to{" "}
            <a className="text-primary" href={`mailto:${siteConfig.email}`}>
              {siteConfig.email}
            </a>
            .
          </TermsSection>
        </div>
      </div>
    </section>
  );
}

function TermsSection({
  title,
  children
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h2 className="text-[28px]">{title}</h2>
      <p>{children}</p>
    </section>
  );
}
